# Generated by Django 5.1.3 on 2024-11-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='reconhecido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponto',
            name='temp_photo',
            field=models.ImageField(blank=True, null=True, upload_to='temp_photos/'),
        ),
    ]
