# Generated by Django 5.1.3 on 2024-11-16 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ponto_reconhecido_ponto_temp_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
    ]
