# Generated by Django 5.1.3 on 2024-11-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_ponto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='distancia',
            field=models.FloatField(blank=True, help_text='Distância do reconhecimento facial para análise', null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='reconhecido',
            field=models.BooleanField(default=False, help_text='Indica se o usuário foi reconhecido com sucesso'),
        ),
    ]
